'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Download, FileText, Loader2, AlertCircle, BarChart3, Code, CheckCircle, Activity } from 'lucide-react';
import { toast } from 'sonner';

interface ReportData {
  htmlContent: string;
  customerName: string;
  reportType: string;
  generatedAt: string;
}

export default function AEOReportPage() {
  const searchParams = useSearchParams();
  const hasAutoGenerated = useRef(false);
  const [customerName, setCustomerName] = useState('');
  const [url, setUrl] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isFetchingReport, setIsFetchingReport] = useState(false);
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [generationSuccess, setGenerationSuccess] = useState(false);
  const [reportId, setReportId] = useState<string | null>(null);

  const generateReport = useCallback(async (nameOverride?: string, urlOverride?: string) => {
    const nameToUse = typeof nameOverride === 'string' ? nameOverride : customerName;
    const urlToUse = typeof urlOverride === 'string' ? urlOverride : url;

    if (!nameToUse.trim()) {
      toast.error('Please enter a customer name');
      return;
    }

    if (!urlToUse.trim()) {
      toast.error('Please enter a website URL');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGenerationSuccess(false);
    setReportData(null);
    setReportId(null);

    try {
      const response = await fetch('/api/aeo-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerName: nameToUse.trim(),
          url: urlToUse.trim(),
          reportType: 'combined',
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate report');
      }

      setReportId(data.reportId);
      setGenerationSuccess(true);
      toast.success('Report generation started!');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setIsGenerating(false);
    }
  }, [customerName, url]);

  useEffect(() => {
    let intervalId: NodeJS.Timeout;

    if (reportId && !reportData) {
      setIsFetchingReport(true);
      const pollReport = async () => {
        try {
          const res = await fetch(`/api/aeo-reports/${reportId}/view`);
          if (res.status === 200) {
            const html = await res.text();
            setReportData({
              htmlContent: html,
              customerName: customerName, // We might want to fetch the actual name if changed
              reportType: 'combined',
              generatedAt: new Date().toISOString()
            });
            setGenerationSuccess(false); // Hide the "Started" card, show report
            setIsFetchingReport(false);
            toast.success('Report ready!');
            clearInterval(intervalId);
          } else if (res.status === 202) {
            // Still processing, continue polling
            console.log('Report still processing...');
          } else {
            // Error or 404
            console.error('Polling error:', res.status);
          }
        } catch (e) {
          console.error('Polling failed', e);
        }
      };

      // Poll immediately then every 3s
      pollReport();
      intervalId = setInterval(pollReport, 3000);
    }

    return () => {
      if (intervalId) clearInterval(intervalId);
    };
  }, [reportId, reportData, customerName]);

  useEffect(() => {
    const paramName = searchParams.get('customerName');
    const paramUrl = searchParams.get('url');
    const auto = searchParams.get('auto');
    const paramReportId = searchParams.get('reportId');

    // If a reportId is provided, fetch that specific report
    if (paramReportId && !reportData && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      setReportId(paramReportId);
      return; // Let the polling effect handle fetching the report
    }

    if (paramName) {
      setCustomerName(paramName);
    }
    if (paramUrl) {
      setUrl(paramUrl);
    }

    // Only auto-generate if explicitly requested via URL params and we haven't already generated
    // Reset the ref when params change to allow re-generation on new navigation
    if (auto === 'true' && paramName && paramUrl && !hasAutoGenerated.current && !reportData) {
      hasAutoGenerated.current = true;
      generateReport(paramName, paramUrl);
    } else if (!auto || !paramName || !paramUrl) {
      // Reset the ref when navigating without auto params
      hasAutoGenerated.current = false;
    }
  }, [searchParams, generateReport, reportData]);

  const loadExistingReport = async () => {
    if (!customerName.trim()) {
      toast.error('Please enter a customer name');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/aeo-report?customerName=${encodeURIComponent(customerName.trim())}&reportType=basic`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to load report');
      }

      setReportData(data);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!reportData) return;

    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error('Please allow popups to download PDF');
        return;
      }

      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>AEO Report - ${reportData.customerName}</title>
          <style>
            @media print {
              body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
              .no-print { display: none !important; }
              .page-break { page-break-before: always; }
              table { page-break-inside: avoid; }
              .card { page-break-inside: avoid; margin-bottom: 20px; }
            }
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #004d99; padding-bottom: 20px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>AEO Report</h1>
            <p>Customer: ${reportData.customerName} | Generated: ${new Date(reportData.generatedAt).toLocaleString()}</p>
          </div>
          ${reportData.htmlContent}
          <div class="footer">
            <p>Generated by Firegeo AEO Analysis System</p>
          </div>
        </body>
        </html>
      `;

      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
      };
      toast.success('PDF download initiated');
    } catch (err) {
      toast.error('Failed to generate PDF');
    }
  };

  return (
      <div className="min-h-screen pl-16 md:pl-0">
          <div className="container mx-auto py-8 px-4">
          <div className="mb-8">
          <h1 className="text-3xl font-bold mb-2">AEO Report Generator</h1>
          <p className="text-muted-foreground">
            Generate comprehensive AEO (Answer Engine Optimization) reports for your clients
          </p>
        </div>

        {isGenerating && (
          <div className="flex flex-col items-center justify-center py-20 space-y-6">
            <Loader2 className="h-16 w-16 animate-spin text-blue-600" />
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-slate-800">Generating AEO Report</h2>
              <p className="text-slate-500 max-w-md mx-auto">
                Analyzing {customerName ? customerName : 'brand'} presence and Answer Engine Optimization metrics...
              </p>
            </div>
          </div>
        )}

        {!isGenerating && generationSuccess && (
          <Card className="border-green-200 bg-green-50">
            <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <div className="p-4 bg-green-100 rounded-full">
                <Loader2 className="h-8 w-8 animate-spin text-green-600" />
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-semibold text-green-800">Generating Report...</h3>
                <p className="text-green-700 max-w-md">
                  Your AEO report is being generated in the background. Please wait, this may take a few minutes.
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {isFetchingReport && (
          <div className="flex flex-col items-center justify-center py-20 space-y-6">
            <Loader2 className="h-16 w-16 animate-spin text-purple-600" />
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-slate-800">Loading Report</h2>
              <p className="text-slate-500 max-w-md mx-auto">
                Fetching your AEO report from the database...
              </p>
            </div>
          </div>
        )}

        {!isGenerating && !isFetchingReport && !generationSuccess && !reportData && !error && (
          <div className="space-y-8">
            <Card className="border-dashed">
              <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
                <div className="p-4 bg-blue-50 rounded-full">
                  <FileText className="h-8 w-8 text-blue-500" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-semibold">Ready to Generate</h3>
                  <p className="text-slate-500 max-w-md">
                    Please launch the AEO Report from a Brand Profile to automatically generate an analysis.
                  </p>
                </div>
              </CardContent>
            </Card>

            <section className="rounded-2xl border bg-white p-8 shadow-sm">
              <h3 className="text-xl font-semibold text-slate-900 mb-2">What's inside your AEO Report</h3>
              <p className="text-sm text-slate-600 mb-6">
                You will receive a comprehensive PDF report containing deep insights to improve your brand's visibility on AI-driven search engines.
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="border rounded-lg p-4 flex gap-3">
                  <BarChart3 className="w-8 h-8 text-blue-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Brand Visibility</h4>
                    <p className="text-sm text-slate-600">
                      Deep dive into how your brand appears across major search engines and AI platforms.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <Activity className="w-8 h-8 text-purple-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">AEO Score & Metrics</h4>
                    <p className="text-sm text-slate-600">
                      Quantitative scoring of your Answer Engine Optimization performance and key metrics.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <Code className="w-8 h-8 text-slate-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Schema Validation</h4>
                    <p className="text-sm text-slate-600">
                      Technical analysis of your structured data implementation to ensure AI readability.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <CheckCircle className="w-8 h-8 text-emerald-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Actionable Insights</h4>
                    <p className="text-sm text-slate-600">
                      Step-by-step recommendations and strategies to improve your standing in AI search results.
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </div>
        )}

        {error && (
          <Card className="border-red-200 bg-red-50">
            <CardContent className="pt-6">
              <div className="flex items-center space-x-2 text-red-700">
                <AlertCircle className="h-4 w-4" />
                <span>{error}</span>
              </div>
            </CardContent>
          </Card>
        )}

        {reportData && (
          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>AEO Report - {reportData.customerName}</CardTitle>
                  <CardDescription>
                    Generated on {new Date(reportData.generatedAt).toLocaleString()} | Type: {reportData.reportType}
                  </CardDescription>
                </div>
                <div className="flex gap-2">
                  <Button
                    onClick={() => {
                      const newWindow = window.open('', '_blank');
                      if (newWindow) {
                        newWindow.document.write(reportData.htmlContent);
                        newWindow.document.close();
                      }
                    }}
                    variant="outline"
                  >
                    <FileText className="mr-2 h-4 w-4" />
                    View Full Report
                  </Button>
                  <Button onClick={downloadPDF} variant="outline">
                    <Download className="mr-2 h-4 w-4" />
                    Download PDF
                  </Button>
                </div>
              </div>
            </CardHeader>
            <CardContent>
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <p className="text-sm text-blue-900">
                  📄 <strong>Report ready!</strong> Click "View Full Report" to open it in a new tab with full rendering and interactivity.
                </p>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}