'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Download, FileText, Loader2, AlertCircle, BarChart3, Code, CheckCircle, Activity, ArrowLeft } from 'lucide-react';
import { toast } from 'sonner';

interface ReportData {
  htmlContent: string;
  customerName: string;
  reportType: string;
  generatedAt: string;
}

export default function AEOReportPage() {
  const searchParams = useSearchParams();
  const hasAutoGenerated = useRef(false);
  const [customerName, setCustomerName] = useState('');
  const [url, setUrl] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isFetchingReport, setIsFetchingReport] = useState(false);
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [generationSuccess, setGenerationSuccess] = useState(false);
  const [reportId, setReportId] = useState<string | null>(null);

  const brandId = searchParams.get('brandId');

  const generateReport = useCallback(async (nameOverride?: string, urlOverride?: string) => {
    const nameToUse = typeof nameOverride === 'string' ? nameOverride : customerName;
    const urlToUse = typeof urlOverride === 'string' ? urlOverride : url;

    if (!nameToUse.trim()) {
      toast.error('Please enter a customer name');
      return;
    }

    if (!urlToUse.trim()) {
      toast.error('Please enter a website URL');
      return;
    }

    setIsGenerating(true);
    setError(null);
    setGenerationSuccess(false);
    setReportData(null);
    setReportId(null);

    try {
      const response = await fetch('/api/aeo-report', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          customerName: nameToUse.trim(),
          url: urlToUse.trim(),
          reportType: 'combined',
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to generate report');
      }

      setReportId(data.reportId);
      setGenerationSuccess(true);
      toast.success('Report generation started!');
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setIsGenerating(false);
    }
  }, [customerName, url]);

  useEffect(() => {
    let intervalId: NodeJS.Timeout;
    let timeoutId: NodeJS.Timeout;
    let attempts = 0;
    const POLL_INTERVAL = 15000; // 15 seconds
    // Max attempts: covers ~15 minutes after the delay
    const MAX_ATTEMPTS = 60; 

    const fetchFullReport = async () => {
      try {
        const res = await fetch(`/api/aeo-reports/${reportId}/view`, {
          headers: { 'Cache-Control': 'no-cache' },
        });
        if (res.status === 200) {
          const html = await res.text();
          setReportData({
            htmlContent: html,
            customerName: customerName, 
            reportType: 'combined',
            generatedAt: new Date().toISOString()
          });
          setGenerationSuccess(false);
          setIsFetchingReport(false);
          toast.success('Report ready!');
        } else {
          setError(`Failed to fetch report content (Status: ${res.status})`);
        }
      } catch (e) {
        setError('Error downloading report content');
      }
    };

    const startPolling = () => {
      // Poll immediately on start
      pollCheck();
      intervalId = setInterval(pollCheck, POLL_INTERVAL);
    };

    const pollCheck = async () => {
      attempts++;
      try {
        // Use lightweight check
        const res = await fetch(`/api/aeo-reports/${reportId}/view?check=true`, {
          headers: { 'Cache-Control': 'no-cache' },
        });

        if (res.status === 200) {
          const data = await res.json();
          if (data.ready) {
            // Report is ready! Stop polling and get content.
            clearInterval(intervalId);
            fetchFullReport();
          } else {
            // Not ready yet (ready: false)
            if (attempts >= MAX_ATTEMPTS) {
              clearInterval(intervalId);
              setIsFetchingReport(false);
              setGenerationSuccess(false);
              setError('Report generation timed out. Please try again.');
            }
            console.log('Report processing... (Check Only)');
          }
        } else if (res.status === 404) {
          // Not found
           clearInterval(intervalId);
           setIsFetchingReport(false);
           setGenerationSuccess(false);
           setError('Report not found.');
        } else {
          // Other error
           console.error('Polling check error:', res.status);
        }
      } catch (e) {
        console.error('Polling check failed', e);
        // Don't stop for one network blip, but maybe count errors?
      }
    };

    if (reportId && !reportData) {
      setIsFetchingReport(true);

      // If we just started generation (generationSuccess is true), wait 2 mins before first poll
      // If we are just reloading the page (generationSuccess might be false but reportId exists), poll immediately
      // We can use a ref or just check generationSuccess state
      
      if (generationSuccess) {
         console.log('Report started. Waiting 2 minutes before starting poll...');
         timeoutId = setTimeout(startPolling, 120000); 
      } else {
         startPolling();
      }
    }

    return () => {
      if (intervalId) clearInterval(intervalId);
      if (timeoutId) clearTimeout(timeoutId);
    };
  }, [reportId, reportData, customerName, generationSuccess]);

  useEffect(() => {
    const paramName = searchParams.get('customerName');
    const paramUrl = searchParams.get('url');
    const auto = searchParams.get('auto');
    const paramReportId = searchParams.get('reportId');

    // If a reportId is provided, fetch that specific report
    if (paramReportId && !reportData && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      setReportId(paramReportId);
      return; // Let the polling effect handle fetching the report
    }

    if (paramName) {
      setCustomerName(paramName);
    }
    if (paramUrl) {
      setUrl(paramUrl);
    }

    // Only auto-generate if explicitly requested via URL params and we haven't already generated
    // Reset the ref when params change to allow re-generation on new navigation
    if (auto === 'true' && paramName && paramUrl && !hasAutoGenerated.current && !reportData) {
      hasAutoGenerated.current = true;
      generateReport(paramName, paramUrl);
    } else if (!auto || !paramName || !paramUrl) {
      // Reset the ref when navigating without auto params
      hasAutoGenerated.current = false;
    }
  }, [searchParams, generateReport, reportData]);

  const loadExistingReport = async () => {
    if (!customerName.trim()) {
      toast.error('Please enter a customer name');
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/aeo-report?customerName=${encodeURIComponent(customerName.trim())}&reportType=basic`);
      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || 'Failed to load report');
      }

      setReportData(data);
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Unknown error occurred';
      setError(errorMessage);
      toast.error(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!reportData) return;

    try {
      const printWindow = window.open('', '_blank');
      if (!printWindow) {
        toast.error('Please allow popups to download PDF');
        return;
      }

      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>AEO Report - ${reportData.customerName}</title>
          <style>
            @media print {
              body { margin: 0; padding: 20px; font-family: Arial, sans-serif; }
              .no-print { display: none !important; }
              .page-break { page-break-before: always; }
              table { page-break-inside: avoid; }
              .card { page-break-inside: avoid; margin-bottom: 20px; }
            }
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #004d99; padding-bottom: 20px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>AEO Report</h1>
            <p>Customer: ${reportData.customerName} | Generated: ${new Date(reportData.generatedAt).toLocaleString()}</p>
          </div>
          ${reportData.htmlContent}
          <div class="footer">
            <p>Generated by Firegeo AEO Analysis System</p>
          </div>
        </body>
        </html>
      `;

      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.onload = () => {
        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 500);
      };
      toast.success('PDF download initiated');
    } catch (err) {
      toast.error('Failed to generate PDF');
    }
  };

  return (
      <div className="min-h-screen pl-16 md:pl-0">
          <div className="container mx-auto py-8 px-4">
          <div className="mb-8">
          {brandId && (
            <Link 
              href={`/brand-profiles/${brandId}`}
              className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-4 transition-colors"
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Profile
            </Link>
          )}
          <h1 className="text-3xl font-bold mb-2">AEO Report Generator</h1>
          <p className="text-muted-foreground">
            Generate comprehensive AEO (Answer Engine Optimization) reports for your clients
          </p>
        </div>

        {isGenerating && (
          <div className="flex flex-col items-center justify-center py-20 space-y-6">
            <Loader2 className="h-16 w-16 animate-spin text-blue-600" />
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-slate-800">Generating AEO Report</h2>
              <p className="text-slate-500 max-w-md mx-auto">
                Analyzing {customerName ? customerName : 'brand'} presence and Answer Engine Optimization metrics...
              </p>
            </div>
          </div>
        )}

        {!isGenerating && generationSuccess && (
          <Card className="border-green-200 bg-green-50">
            <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
              <div className="p-4 bg-green-100 rounded-full">
                <Loader2 className="h-8 w-8 animate-spin text-green-600" />
              </div>
              <div className="space-y-2">
                <h3 className="text-xl font-semibold text-green-800">Generating Report...</h3>
                <p className="text-green-700 max-w-md">
                  Your AEO report is being generated in the background. Please wait, this may take a few minutes.
                </p>
              </div>
            </CardContent>
          </Card>
        )}

        {isFetchingReport && !generationSuccess && (
          <div className="flex flex-col items-center justify-center py-20 space-y-6">
            <Loader2 className="h-16 w-16 animate-spin text-purple-600" />
            <div className="text-center space-y-2">
              <h2 className="text-2xl font-bold text-slate-800">Loading Report</h2>
              <p className="text-slate-500 max-w-md mx-auto">
                Fetching your AEO report from the database...
              </p>
            </div>
          </div>
        )}

        {!isGenerating && !isFetchingReport && !generationSuccess && !reportData && !error && (
          <div className="space-y-8">
            <Card className="border-dashed">
              <CardContent className="flex flex-col items-center justify-center py-12 text-center space-y-4">
                <div className="p-4 bg-blue-50 rounded-full">
                  <FileText className="h-8 w-8 text-blue-500" />
                </div>
                <div className="space-y-2">
                  <h3 className="text-xl font-semibold">Ready to Generate</h3>
                  <p className="text-slate-500 max-w-md">
                    Please launch the AEO Report from a Brand Profile to automatically generate an analysis.
                  </p>
                </div>
              </CardContent>
            </Card>

            <section className="rounded-2xl border bg-white p-8 shadow-sm">
              <h3 className="text-xl font-semibold text-slate-900 mb-6">What's included in your AEO Report</h3>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="border rounded-lg p-4 flex gap-3">
                  <BarChart3 className="w-8 h-8 text-blue-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Brand Visibility Analysis</h4>
                    <p className="text-sm text-slate-600">
                      Deep dive into how your brand appears across major search engines and AI platforms. Get detailed metrics on visibility scores and positioning.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <Activity className="w-8 h-8 text-purple-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">AEO Score & Metrics</h4>
                    <p className="text-sm text-slate-600">
                      Quantitative scoring of your Answer Engine Optimization performance including visibility score, sentiment analysis, and share of voice metrics.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <Code className="w-8 h-8 text-slate-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Technical & Schema Analysis</h4>
                    <p className="text-sm text-slate-600">
                      Technical analysis of your website structure and schema.org markup implementation to ensure proper AI readability and indexing.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3">
                  <CheckCircle className="w-8 h-8 text-emerald-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Actionable Recommendations</h4>
                    <p className="text-sm text-slate-600">
                      Step-by-step optimization strategies and prioritized action items to improve your standing in AI search results.
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </div>
        )}

        {error && (
          <Card className="border-red-200 bg-red-50">
            <CardContent className="pt-6">
              <div className="flex items-center space-x-2 text-red-700">
                <AlertCircle className="h-4 w-4" />
                <span>{error}</span>
              </div>
            </CardContent>
          </Card>
        )}

        {reportData && (
          <div className="space-y-6">
            {/* Report Header */}
            <Card>
              <CardHeader>
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  <div>
                    <CardTitle className="text-2xl">AEO Report - {reportData.customerName}</CardTitle>
                    <CardDescription className="mt-2">
                      Generated on {new Date(reportData.generatedAt).toLocaleString()}
                    </CardDescription>
                  </div>
                  <div className="flex gap-2 flex-wrap">
                    <Button
                      onClick={() => {
                        const newWindow = window.open('', '_blank');
                        if (newWindow) {
                          newWindow.document.write(reportData.htmlContent);
                          newWindow.document.close();
                        }
                      }}
                      className="bg-blue-600 hover:bg-blue-700"
                    >
                      <FileText className="mr-2 h-4 w-4" />
                      View Full Report
                    </Button>
                    <Button onClick={downloadPDF} variant="outline">
                      <Download className="mr-2 h-4 w-4" />
                      Download PDF
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                  <p className="text-sm text-blue-900">
                    📄 <strong>Report ready!</strong> Click "View Full Report" to open it in a new tab with full rendering and interactivity, or "Download PDF" to save it.
                  </p>
                </div>
              </CardContent>
            </Card>

            {/* Report Contents Tabs */}
            <section className="rounded-2xl border bg-white p-8 shadow-sm">
              <h3 className="text-xl font-semibold text-slate-900 mb-6">What's in this Report</h3>
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                <div className="border rounded-lg p-4 flex gap-3 hover:shadow-md transition">
                  <BarChart3 className="w-8 h-8 text-blue-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Brand Visibility Analysis</h4>
                    <p className="text-sm text-slate-600 mt-1">
                      Comprehensive analysis of how your brand appears across search engines and AI platforms, including visibility scores, ranking positions, and competitive benchmarking.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3 hover:shadow-md transition">
                  <Activity className="w-8 h-8 text-purple-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">AEO Score & Metrics</h4>
                    <p className="text-sm text-slate-600 mt-1">
                      Quantitative performance metrics including Answer Engine Optimization score, sentiment analysis, share of voice, and competitive positioning data.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3 hover:shadow-md transition">
                  <Code className="w-8 h-8 text-slate-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Technical & Schema Analysis</h4>
                    <p className="text-sm text-slate-600 mt-1">
                      Technical audit of your website structure, schema.org markup validation, structured data implementation, and AI crawler readability assessment.
                    </p>
                  </div>
                </div>
                <div className="border rounded-lg p-4 flex gap-3 hover:shadow-md transition">
                  <CheckCircle className="w-8 h-8 text-emerald-600 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-lg">Actionable Recommendations</h4>
                    <p className="text-sm text-slate-600 mt-1">
                      Prioritized optimization strategies and step-by-step action items to improve your brand visibility and performance in AI-driven search results.
                    </p>
                  </div>
                </div>
              </div>
            </section>
          </div>
        )}
      </div>
    </div>
  );
}